[workspace]
members = [
    "core",
    "cli",
    "daemon",
    "tui",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["ereinaimer"]
description = "Fast, secure and easy to use text expander and keyboard automation tool"
repository = "https://github.com/ereinaimer/taurine"
license-file = "LICENSE"

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }