[workspace]
members = [
    "core",
    "cli",
    "daemon",
    "tui",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["ereinaimer"]
description = "Fast, secure and easy to use text expander and keyboard automation tool"
repository = "https://github.com/ereinaimer/taurine"
license-file = "LICENSE"
publish = false

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time", "local-time"] }

[profile.release]
opt-level = "z"      # Optimize for size
lto = true           # Link Time Optimization (huge win for size)
codegen-units = 1    # Better optimization at the cost of compile time
panic = "abort"      # Remove unwinding code (saves size)
strip = true         # Strip symbols from the binary

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
