[package]
name = "taurine"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
taurine_core = { path = "../core" }
taurine_daemon = { path = "../daemon" }
taurine_tui = { path = "../tui" }
clap = { version = "4", features = ["derive"] }
time = { version = "0.3", features = ["macros", "local-offset"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
color-eyre = { version = "0.6.5", features = ["default"] }
tracing-error = "0.2.1"
service-manager = "0.11.0"

[target."cfg(windows)".dependencies]
sysinfo = "0.38.4"
winreg = "0.56.0"
