blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/ereinaimer/taurine/discussions/new?category=q-a
    about: Need help or have a question about Taurine? Ask it here.