use crate::platform::ClipboardManager;
use objc2_app_kit::NSPasteboard;
use objc2_foundation::{NSData, NSString};

pub struct MacosClipboard;

impl ClipboardManager for MacosClipboard {
    fn get_text(&mut self) -> Result<String, String> {
        // SAFETY: Interaction with the Objective-C AppKit runtime is memory-safe because we only access the general pasteboard
        // on the main thread and read its text representation, which is validated by the `objc2` type safety.
        unsafe {
            let pb = NSPasteboard::generalPasteboard();
            let ns_str = pb.stringForType(objc2_app_kit::NSPasteboardTypeString);
            if let Some(ns_str) = ns_str {
                Ok(ns_str.to_string())
            } else {
                Ok(String::new())
            }
        }
    }

    fn set_text(&mut self, text: &str) -> Result<(), String> {
        // SAFETY: Interaction with the Objective-C AppKit runtime. We invoke `clearContents` and `setString:forType:`
        // to write text, and declare additional transient mime metadata. All pointer values are validated, and the local
        // references are managed by `objc2`'s reference counting.
        unsafe {
            let pb = NSPasteboard::generalPasteboard();
            pb.clearContents();

            let ns_text = NSString::from_str(text);
            let success = pb.setString_forType(&ns_text, objc2_app_kit::NSPasteboardTypeString);
            if !success {
                return Err("Failed to set pasteboard string".to_string());
            }

            let ns_empty = NSData::new();

            // Set transient pasteboard types to prevent clipboard managers from recording the data
            let transient_type = NSString::from_str("org.nspasteboard.TransientType");
            pb.setData_forType(Some(&ns_empty), &transient_type);

            let concealed_type = NSString::from_str("org.nspasteboard.ConcealedType");
            pb.setData_forType(Some(&ns_empty), &concealed_type);

            let auto_generated_type = NSString::from_str("org.nspasteboard.AutoGeneratedType");
            pb.setData_forType(Some(&ns_empty), &auto_generated_type);

            let pm_transient_type = NSString::from_str("de.petermaurer.TransientPasteboardType");
            pb.setData_forType(Some(&ns_empty), &pm_transient_type);

            let ti4me_type = NSString::from_str("com.typeit4me.clipping");
            pb.setData_forType(Some(&ns_empty), &ti4me_type);

            Ok(())
        }
    }

    fn set_image(&mut self, bytes: &[u8], mime_type: &str) -> Result<(), String> {
        // SAFETY: Interaction with the Objective-C AppKit runtime. We invoke `clearContents` and `setData_forType:`
        // to write the raw PNG/JPEG image bytes. Local references are managed by `objc2`.
        unsafe {
            let pb = NSPasteboard::generalPasteboard();
            pb.clearContents();

            let ns_data = NSData::with_bytes(bytes);

            // Map MIME type to standard macOS pasteboard types
            let pb_type = if mime_type == "image/jpeg" {
                // "public.jpeg"
                &NSString::from_str("public.jpeg")
            } else {
                objc2_app_kit::NSPasteboardTypePNG
            };

            let success = pb.setData_forType(Some(&ns_data), pb_type);
            if !success {
                return Err("Failed to set pasteboard image data".to_string());
            }

            // Also set transient pasteboard types to prevent clipboard managers from recording the image
            let ns_empty = NSData::new();

            let transient_type = NSString::from_str("org.nspasteboard.TransientType");
            pb.setData_forType(Some(&ns_empty), &transient_type);

            let concealed_type = NSString::from_str("org.nspasteboard.ConcealedType");
            pb.setData_forType(Some(&ns_empty), &concealed_type);

            let auto_generated_type = NSString::from_str("org.nspasteboard.AutoGeneratedType");
            pb.setData_forType(Some(&ns_empty), &auto_generated_type);

            let pm_transient_type = NSString::from_str("de.petermaurer.TransientPasteboardType");
            pb.setData_forType(Some(&ns_empty), &pm_transient_type);

            let ti4me_type = NSString::from_str("com.typeit4me.clipping");
            pb.setData_forType(Some(&ns_empty), &ti4me_type);

            Ok(())
        }
    }
}
