use crate::platform::ClipboardManager;
use objc2_app_kit::NSPasteboard;
use objc2_foundation::{NSData, NSString};

pub struct MacosClipboard;

impl ClipboardManager for MacosClipboard {
    fn get_text(&mut self) -> Result<String, String> {
        // SAFETY: Interaction with the Objective-C AppKit runtime is memory-safe because we only access the general pasteboard
        // on the main thread and read its text representation, which is validated by the `objc2` type safety.
        unsafe {
            let pb = NSPasteboard::generalPasteboard();
            let ns_str = pb.stringForType(objc2_app_kit::NSPasteboardTypeString);
            if let Some(ns_str) = ns_str {
                Ok(ns_str.to_string())
            } else {
                Ok(String::new())
            }
        }
    }

    fn set_text(&mut self, text: &str) -> Result<(), String> {
        // SAFETY: Interaction with the Objective-C AppKit runtime. We invoke `clearContents` and `setString:forType:`
        // to write text, and declare additional transient mime metadata. All pointer values are validated, and the local
        // references are managed by `objc2`'s reference counting.
        unsafe {
            let pb = NSPasteboard::generalPasteboard();
            pb.clearContents();

            let ns_text = NSString::from_str(text);
            let success = pb.setString_forType(&ns_text, objc2_app_kit::NSPasteboardTypeString);
            if !success {
                return Err("Failed to set pasteboard string".to_string());
            }

            let ns_empty = NSData::new();

            // Set transient pasteboard types to prevent clipboard managers from recording the data
            let transient_type = NSString::from_str("org.nspasteboard.TransientType");
            pb.setData_forType(Some(&ns_empty), &transient_type);

            let concealed_type = NSString::from_str("org.nspasteboard.ConcealedType");
            pb.setData_forType(Some(&ns_empty), &concealed_type);

            let auto_generated_type = NSString::from_str("org.nspasteboard.AutoGeneratedType");
            pb.setData_forType(Some(&ns_empty), &auto_generated_type);

            let pm_transient_type = NSString::from_str("de.petermaurer.TransientPasteboardType");
            pb.setData_forType(Some(&ns_empty), &pm_transient_type);

            let ti4me_type = NSString::from_str("com.typeit4me.clipping");
            pb.setData_forType(Some(&ns_empty), &ti4me_type);

            Ok(())
        }
    }

    fn set_html(&mut self, html: &str, plaintext: &str) -> Result<(), String> {
        // SAFETY: Interaction with the Objective-C AppKit runtime. We invoke `clearContents` and `setString:forType:`
        // to write HTML and plaintext strings, and declare additional transient metadata. All local references are managed
        // by objc2's reference counting.
        unsafe {
            let pb = NSPasteboard::generalPasteboard();
            pb.clearContents();

            let ns_plain = NSString::from_str(plaintext);
            let ns_html = NSString::from_str(html);

            let success_plain =
                pb.setString_forType(&ns_plain, objc2_app_kit::NSPasteboardTypeString);
            let html_type = NSString::from_str("public.html");
            let success_html = pb.setString_forType(&ns_html, &html_type);

            if !success_plain || !success_html {
                return Err("Failed to set pasteboard HTML/string".to_string());
            }

            let ns_empty = NSData::new();

            let transient_type = NSString::from_str("org.nspasteboard.TransientType");
            pb.setData_forType(Some(&ns_empty), &transient_type);

            let concealed_type = NSString::from_str("org.nspasteboard.ConcealedType");
            pb.setData_forType(Some(&ns_empty), &concealed_type);

            let auto_generated_type = NSString::from_str("org.nspasteboard.AutoGeneratedType");
            pb.setData_forType(Some(&ns_empty), &auto_generated_type);

            let pm_transient_type = NSString::from_str("de.petermaurer.TransientPasteboardType");
            pb.setData_forType(Some(&ns_empty), &pm_transient_type);

            let ti4me_type = NSString::from_str("com.typeit4me.clipping");
            pb.setData_forType(Some(&ns_empty), &ti4me_type);

            Ok(())
        }
    }

    fn set_image_file(&mut self, path: &std::path::Path) -> Result<(), String> {
        let bytes = std::fs::read(path).map_err(|e| format!("Failed to read image file: {}", e))?;
        let path_str = path.to_string_lossy();

        // SAFETY: Interaction with the Objective-C AppKit runtime. We invoke `clearContents`,
        // and `setData_forType` / `setPropertyList_forType` to write raw image bytes and file path.
        unsafe {
            let pb = NSPasteboard::generalPasteboard();
            pb.clearContents();

            let ns_data = NSData::with_bytes(&bytes);

            // Map file extension to standard macOS pasteboard types
            let pb_type = if path_str.ends_with(".jpg") || path_str.ends_with(".jpeg") {
                // "public.jpeg"
                &NSString::from_str("public.jpeg")
            } else {
                objc2_app_kit::NSPasteboardTypePNG
            };

            pb.setData_forType(Some(&ns_data), pb_type);

            // Write file URL for drag-and-drop / file paste compatibility
            let url_string = format!("file://{}", path_str);
            let ns_url = NSString::from_str(&url_string);
            pb.setString_forType(&ns_url, objc2_app_kit::NSPasteboardTypeFileURL);

            // Also set transient pasteboard types to prevent clipboard managers from recording the image
            let ns_empty = NSData::new();

            let transient_type = NSString::from_str("org.nspasteboard.TransientType");
            pb.setData_forType(Some(&ns_empty), &transient_type);

            let concealed_type = NSString::from_str("org.nspasteboard.ConcealedType");
            pb.setData_forType(Some(&ns_empty), &concealed_type);

            let auto_generated_type = NSString::from_str("org.nspasteboard.AutoGeneratedType");
            pb.setData_forType(Some(&ns_empty), &auto_generated_type);

            let pm_transient_type = NSString::from_str("de.petermaurer.TransientPasteboardType");
            pb.setData_forType(Some(&ns_empty), &pm_transient_type);

            let ti4me_type = NSString::from_str("com.typeit4me.clipping");
            pb.setData_forType(Some(&ns_empty), &ti4me_type);

            Ok(())
        }
    }
}
