[package]
name = "taurine_daemon"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
taurine_core = { path = "../core" }
tracing = { workspace = true }
tokio = { version = "1.0", features = ["full"] }
tonic = "0.12"
rdev = "0.5.3"
arboard = "3.4.1"
serde_json = "1.0.149"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_System_DataExchange",
    "Win32_System_Memory",
] }
