use rand::RngExt;

struct NamePool {
    first_names: &'static [&'static str],
    last_names: &'static [&'static str],
}

const NAME_POOLS: &[NamePool] = &[
    // Western / English
    NamePool {
        first_names: &[
            "James",
            "Mary",
            "John",
            "Patricia",
            "Robert",
            "Jennifer",
            "Michael",
            "Linda",
            "David",
            "Elizabeth",
            "William",
            "Barbara",
            "Richard",
            "Susan",
            "Joseph",
            "Jessica",
            "Thomas",
            "Sarah",
            "Christopher",
            "Karen",
            "Charles",
            "Lisa",
            "Daniel",
            "Nancy",
            "Matthew",
            "Betty",
            "Anthony",
            "Margaret",
            "Mark",
            "Sandra",
            "Donald",
            "Ashley",
            "Steven",
            "Dorothy",
            "Paul",
            "Kimberly",
            "Andrew",
            "Emily",
            "Joshua",
            "Donna",
            "Kenneth",
            "Michelle",
            "Kevin",
            "Carol",
            "Brian",
            "Amanda",
            "George",
            "Melissa",
            "Timothy",
            "Deborah",
            "Edward",
            "Laura",
            "Jason",
            "Helen",
            "Jeffrey",
            "Angela",
            "Ryan",
            "Sharon",
            "Jacob",
            "Rebecca",
            "Gary",
            "Christine",
            "Nicholas",
            "Janet",
            "Eric",
            "Catherine",
            "Jonathan",
            "Virginia",
            "Stephen",
            "Kathleen",
            "Larry",
            "Pamela",
            "Justin",
            "Martha",
            "Scott",
            "Debra",
            "Brandon",
            "Joyce",
            "Benjamin",
            "Diane",
            "Samuel",
            "Rachel",
            "Raymond",
            "Julie",
            "Gregory",
            "Hannah",
            "Frank",
            "Olivia",
            "Alexander",
            "Sophia",
            "Patrick",
            "Isabella",
            "Jack",
            "Charlotte",
            "Henry",
            "Grace",
            "Oscar",
            "Amelia",
            "Lucas",
            "Ella",
            "Aiden",
            "Aria",
            "Jackson",
            "Chloe",
        ],
        last_names: &[
            "Smith",
            "Johnson",
            "Williams",
            "Brown",
            "Jones",
            "Garcia",
            "Miller",
            "Davis",
            "Wilson",
            "Anderson",
            "Thomas",
            "Taylor",
            "Moore",
            "Jackson",
            "Martin",
            "Lee",
            "Thompson",
            "White",
            "Harris",
            "Clark",
            "Lewis",
            "Robinson",
            "Walker",
            "Young",
            "Allen",
            "King",
            "Wright",
            "Scott",
            "Green",
            "Baker",
            "Hall",
            "Adams",
            "Nelson",
            "Hill",
            "Campbell",
            "Mitchell",
            "Carter",
            "Roberts",
            "Phillips",
            "Evans",
            "Turner",
            "Parker",
            "Edwards",
            "Collins",
            "Stewart",
            "Morris",
            "Murphy",
            "Cook",
            "Rogers",
            "Morgan",
            "Peterson",
            "Cooper",
            "Reed",
            "Bailey",
            "Bell",
            "Howard",
            "Ward",
            "Brooks",
            "Gray",
            "James",
            "Watson",
            "Hughes",
            "Price",
            "Butler",
            "Barnes",
            "Coleman",
            "Jenkins",
            "Perry",
            "Powell",
            "Long",
            "Patterson",
            "Washington",
        ],
    },
    // Spanish / Latin American
    NamePool {
        first_names: &[
            "Santiago",
            "Valentina",
            "Mateo",
            "Camila",
            "Sebastián",
            "Sofía",
            "Diego",
            "Luna",
            "Gabriel",
            "Martina",
            "Alejandro",
            "Victoria",
            "Jorge",
            "Regina",
            "Luis",
            "Fernanda",
            "Carlos",
            "Manuela",
            "Pedro",
            "Catalina",
            "Miguel",
            "Gabriela",
            "José",
            "Mariana",
            "Rafael",
            "Paula",
            "Antonio",
            "Adriana",
            "Francisco",
            "Daniela",
            "Juan",
            "Esperanza",
            "Manuel",
            "Carolina",
            "Pablo",
            "Verónica",
            "Ángel",
            "Concepción",
            "Héctor",
            "Isabella",
        ],
        last_names: &[
            "García",
            "Fernández",
            "López",
            "Martínez",
            "Rodríguez",
            "Sánchez",
            "González",
            "Pérez",
            "Muñoz",
            "Romero",
            "Torres",
            "Jiménez",
            "Ruiz",
            "Moreno",
            "Álvarez",
            "Díaz",
            "Ortiz",
            "Medina",
            "Castro",
            "Gutiérrez",
            "Reyes",
            "Mendoza",
            "Aguilar",
            "Vega",
            "Silva",
            "Guerrero",
            "Ramos",
            "Cruz",
            "Morales",
            "Ortega",
            "Navarro",
            "Delgado",
            "Herrera",
            "Flores",
            "Marín",
            "Peña",
            "Santos",
            "Vargas",
            "Rojas",
        ],
    },
    // French
    NamePool {
        first_names: &[
            "Antoine",
            "Léa",
            "Pierre",
            "Emma",
            "Nicolas",
            "Louise",
            "Luc",
            "Chloé",
            "Benoît",
            "Alice",
            "Philippe",
            "Camille",
            "Julien",
            "Sarah",
            "Clément",
            "Manon",
            "Vincent",
            "Anaïs",
            "Mathieu",
            "Juliette",
            "Alexandre",
            "Océane",
            "François",
            "Margot",
            "Romain",
            "Julie",
            "Laurent",
            "Marie",
            "Olivier",
            "Sophie",
            "Stéphane",
            "Céline",
        ],
        last_names: &[
            "Bernard",
            "Dubois",
            "Petit",
            "Durand",
            "Leroy",
            "Moreau",
            "Simon",
            "Laurent",
            "Lefebvre",
            "Michel",
            "David",
            "Bertrand",
            "Roux",
            "Vincent",
            "Fournier",
            "Morel",
            "Girard",
            "Andre",
            "Mercier",
            "Dupont",
            "Lambert",
            "Bonnet",
            "Francois",
            "Rousseau",
            "Blanc",
            "Garnier",
            "Henry",
            "Faure",
            "Gauthier",
            "Perrin",
            "Charpentier",
        ],
    },
    // German
    NamePool {
        first_names: &[
            "Felix",
            "Hannah",
            "Leon",
            "Emma",
            "Lukas",
            "Sophie",
            "Maximilian",
            "Lea",
            "Finn",
            "Maja",
            "Elias",
            "Lena",
            "Noah",
            "Lina",
            "Simon",
            "Clara",
            "Jonas",
            "Mia",
            "Luis",
            "Emilia",
            "Henry",
            "Marie",
            "Oskar",
            "Anna",
            "Theo",
            "Lilly",
            "Ben",
            "Frieda",
            "Moritz",
            "Nele",
            "Emil",
            "Greta",
        ],
        last_names: &[
            "Schmidt",
            "Müller",
            "Schneider",
            "Fischer",
            "Weber",
            "Wagner",
            "Becker",
            "Hoffmann",
            "Schäfer",
            "Koch",
            "Bauer",
            "Richter",
            "Wolf",
            "Zimmermann",
            "Braun",
            "Schulz",
            "Krüger",
            "Hartmann",
            "Lange",
            "Huber",
            "Lehmann",
            "Köhler",
            "Herrmann",
            "Peters",
            "Fuchs",
            "Jäger",
            "Vogel",
            "Stein",
            "Klein",
            "Arnold",
            "Bergmann",
            "Schmitt",
        ],
    },
    // Italian
    NamePool {
        first_names: &[
            "Marco",
            "Sofia",
            "Alessandro",
            "Giulia",
            "Lorenzo",
            "Aurora",
            "Matteo",
            "Alice",
            "Michele",
            "Ginevra",
            "Francesco",
            "Beatrice",
            "Tommaso",
            "Valeria",
            "Leonardo",
            "Greta",
            "Riccardo",
            "Vittoria",
            "Edoardo",
            "Chiara",
            "Federico",
            "Martina",
            "Giuseppe",
            "Cinzia",
            "Simone",
            "Gaia",
            "Davide",
            "Anna",
            "Niccolò",
            "Giada",
            "Luca",
            "Noemi",
        ],
        last_names: &[
            "Rossi",
            "Russo",
            "Ferrari",
            "Esposito",
            "Bianchi",
            "Romano",
            "Colombo",
            "Ricci",
            "Marino",
            "Greco",
            "Bruno",
            "Gallo",
            "Conti",
            "Costa",
            "Mancini",
            "Barbieri",
            "Fontana",
            "Rinaldi",
            "Caruso",
            "Moretti",
            "Donati",
            "Leone",
            "Santoro",
            "Pellegrini",
            "Messina",
            "Fabbri",
            "Rizzi",
            "Longo",
            "Martini",
            "Coppola",
            "De Luca",
            "Parisi",
        ],
    },
    // Japanese
    NamePool {
        first_names: &[
            "Hiroshi", "Yuki", "Takashi", "Miyuki", "Kenji", "Sakura", "Ryo", "Akiko", "Satoshi",
            "Kyoko", "Takeshi", "Yoko", "Kazuki", "Megumi", "Shinji", "Miki", "Daiki", "Nana",
            "Shota", "Aoi", "Koji", "Haruka", "Takuya", "Rina", "Yusuke", "Misaki", "Ryota",
            "Yuna", "Kenta", "Moe", "Masashi", "Saki",
        ],
        last_names: &[
            "Sato",
            "Suzuki",
            "Tanaka",
            "Watanabe",
            "Ito",
            "Yamamoto",
            "Nakamura",
            "Ogawa",
            "Kato",
            "Yoshida",
            "Yamada",
            "Sasaki",
            "Yamaguchi",
            "Matsumoto",
            "Inoue",
            "Kimura",
            "Hayashi",
            "Shimizu",
            "Abe",
            "Mori",
            "Ikeda",
            "Hashimoto",
            "Yamashita",
            "Ishikawa",
            "Nakajima",
            "Maeda",
            "Fujita",
            "Ogata",
            "Ono",
            "Ueda",
            "Ishida",
            "Kondo",
        ],
    },
    // Chinese
    NamePool {
        first_names: &[
            "Wei", "Li", "Jun", "Yan", "Ming", "Fang", "Lei", "Hong", "Tao", "Xia", "Long", "Yue",
            "Chen", "Lin", "Hao", "Mei", "Peng", "Xiu", "Jian", "Lan", "Feng", "Juan", "Gang",
            "Ping", "Qiang", "Na", "Yong", "Rong", "Bin", "Ting", "Kai", "Ying",
        ],
        last_names: &[
            "Wang", "Li", "Zhang", "Liu", "Chen", "Yang", "Huang", "Zhao", "Wu", "Zhou", "Xu",
            "Sun", "Ma", "Zhu", "Hu", "Lin", "Guo", "He", "Gao", "Luo", "Zheng", "Liang", "Xie",
            "Song", "Tang", "Han", "Cao", "Peng", "Cai", "Pan", "Tian", "Deng",
        ],
    },
    // Indian
    NamePool {
        first_names: &[
            "Arjun", "Priya", "Rahul", "Ananya", "Vikram", "Deepika", "Raj", "Anika", "Amit",
            "Sneha", "Vijay", "Pooja", "Ravi", "Neha", "Sanjay", "Kavita", "Rohit", "Sunita",
            "Aakash", "Divya", "Manish", "Anjali", "Suresh", "Lakshmi", "Nitin", "Meera", "Akash",
            "Shweta", "Rakesh", "Nandini", "Gaurav", "Pallavi",
        ],
        last_names: &[
            "Sharma",
            "Patel",
            "Singh",
            "Kumar",
            "Verma",
            "Gupta",
            "Reddy",
            "Joshi",
            "Rao",
            "Nair",
            "Menon",
            "Iyer",
            "Chopra",
            "Mehta",
            "Das",
            "Bose",
            "Sengupta",
            "Banerjee",
            "Mukherjee",
            "Deshmukh",
            "Kulkarni",
            "Pillai",
            "Kapoor",
            "Malhotra",
            "Agarwal",
            "Saxena",
            "Trivedi",
            "Choudhury",
            "Srinivasan",
            "Subramanian",
            "Mishra",
            "Pandey",
        ],
    },
    // Arabic / Middle Eastern
    NamePool {
        first_names: &[
            "Mohammed", "Fatima", "Ahmed", "Aisha", "Ali", "Mariam", "Omar", "Zainab", "Hassan",
            "Noor", "Hussein", "Layla", "Karim", "Amira", "Tariq", "Nadia", "Khalid", "Samira",
            "Youssef", "Rania", "Ibrahim", "Hala", "Mahmoud", "Lina", "Saeed", "Dalia", "Abdullah",
            "Mona", "Rashid", "Nour", "Fahd", "Hind",
        ],
        last_names: &[
            "Hassan", "Hussein", "Abdullah", "Nasser", "Saleh", "Youssef", "Farid", "Rashid",
            "Jabir", "Karam", "Nour", "Zaid", "Tariq", "Malik", "Nassar", "Fahd", "Salam", "Aziz",
            "Hadi", "Rahim", "Karim", "Qadir", "Kamel", "Suleiman", "Nimr", "Qasim", "Bashar",
            "Jamil", "Tawfiq", "Radi", "Salman",
        ],
    },
    // Scandinavian
    NamePool {
        first_names: &[
            "Erik", "Astrid", "Magnus", "Freja", "Lars", "Ingrid", "Anders", "Sigrid", "Bjorn",
            "Liv", "Nils", "Elsa", "Sven", "Maja", "Olav", "Tova", "Henrik", "Ida", "Oskar",
            "Alma", "Axel", "Ebba", "Emil", "Stina", "Karl", "Linnea", "Gustav", "Klara", "Johan",
            "Moa", "Per", "Saga",
        ],
        last_names: &[
            "Andersen",
            "Johansson",
            "Nilsson",
            "Eriksson",
            "Larsson",
            "Olsson",
            "Karlsson",
            "Hansen",
            "Jensen",
            "Pedersen",
            "Nielsen",
            "Christensen",
            "Rasmussen",
            "Svensson",
            "Gustafsson",
            "Berg",
            "Lindberg",
            "Forsberg",
            "Lund",
            "Holm",
            "Björk",
            "Ek",
            "Ström",
            "Löfgren",
            "Axelsson",
            "Bergström",
            "Lindqvist",
            "Lundberg",
            "Norberg",
            "Sandberg",
        ],
    },
    // Russian / Eastern European
    NamePool {
        first_names: &[
            "Alexei",
            "Anastasia",
            "Dmitri",
            "Olga",
            "Ivan",
            "Tatiana",
            "Vladimir",
            "Natasha",
            "Boris",
            "Yelena",
            "Sergei",
            "Irina",
            "Nikolai",
            "Svetlana",
            "Mikhail",
            "Ekaterina",
            "Andrei",
            "Galina",
            "Pavel",
            "Marina",
            "Yuri",
            "Nina",
            "Konstantin",
            "Sonya",
            "Roman",
            "Larisa",
            "Viktor",
            "Valentina",
            "Leonid",
            "Tamara",
            "Grigori",
            "Alla",
        ],
        last_names: &[
            "Ivanov",
            "Smirnov",
            "Kuznetsov",
            "Popov",
            "Vasilyev",
            "Petrov",
            "Sokolov",
            "Mikhailov",
            "Novikov",
            "Fedorov",
            "Morozov",
            "Volkov",
            "Alekseyev",
            "Lebedev",
            "Semyonov",
            "Yegorov",
            "Pavlov",
            "Kozlov",
            "Stepanov",
            "Nikolayev",
            "Orlov",
            "Andreyev",
            "Makarov",
            "Zakharov",
            "Zaitsev",
            "Solovyov",
            "Baranov",
            "Zhukov",
            "Frolov",
            "Kiselev",
            "Sorokin",
            "Krylov",
        ],
    },
    // African / Yoruba / Igbo / Swahili / Zulu
    NamePool {
        first_names: &[
            "Kwame",
            "Amina",
            "Chidi",
            "Ngozi",
            "Kofi",
            "Zanele",
            "Amara",
            "Kemi",
            "Musa",
            "Chimamanda",
            "Simba",
            "Thandiwe",
            "Oluwaseun",
            "Yaa",
            "Jabari",
            "Nyala",
            "Ekow",
            "Adaeze",
            "Tendai",
            "Makena",
            "Kwesi",
            "Sipho",
            "Babatunde",
            "Nkechi",
            "Chinua",
            "Akua",
            "Zuri",
            "Ifeanyi",
            "Barack",
            "Malaika",
            "Osei",
            "Chioma",
        ],
        last_names: &[
            "Mensah", "Okafor", "Nkosi", "Abebe", "Ochieng", "Kamau", "Diop", "Toure", "Keita",
            "Traore", "Cisse", "Diallo", "Mbeki", "Ndlovu", "Dube", "Zulu", "Kone", "Bamba",
            "Sarr", "Faye", "Mboya", "Kenyatta", "Osei", "Asante", "Adebayo", "Okonkwo", "Eze",
            "Chukwu", "Ibrahim", "Otieno", "Balogun", "Sow",
        ],
    },
    // Korean
    NamePool {
        first_names: &[
            "Minho", "Soojin", "Sungmin", "Jiwon", "Hyunwoo", "Eunjoo", "Taehyung", "Miae",
            "Seunggi", "Bora", "Donghyun", "Suyon", "Youngjae", "Hyemi", "Kibum", "Nari", "Jinho",
            "Eunji", "Sangmin", "Hyejin", "Kyungsoo", "Yuna", "Changmin", "Sora", "Woobin",
            "Nayeon", "Jaesung", "Minji", "Hyungsik", "Seoyeon", "Kwangho", "Bomi",
        ],
        last_names: &[
            "Kim", "Park", "Lee", "Choi", "Jung", "Kang", "Cho", "Yoon", "Jang", "Lim", "Han",
            "Oh", "Shin", "Seo", "Kwon", "Hwang", "Ahn", "Song", "Yoo", "Hong", "Moon", "Yang",
            "Bae", "Na", "Ko", "Cha", "Ryu", "Suh", "Noh", "Roh", "Byun", "Jeon",
        ],
    },
    // Turkish
    NamePool {
        first_names: &[
            "Mehmet", "Ayse", "Mustafa", "Fatma", "Ahmet", "Elif", "Kemal", "Zeynep", "Emre",
            "Merve", "Burak", "Gulsen", "Cem", "Derya", "Eren", "Berna", "Hakan", "Sibel", "Tolga",
            "Pinar", "Ozgur", "Aylin", "Murat", "Asli", "Can", "Deniz", "Ali", "Sevgi", "Oguz",
            "Nazli", "Serkan", "Yesim",
        ],
        last_names: &[
            "Yilmaz", "Demir", "Kaya", "Celik", "Ozturk", "Aydin", "Sahin", "Yildiz", "Kara",
            "Aslan", "Cetin", "Koc", "Dogan", "Polat", "Ozdemir", "Arslan", "Guler", "Aksoy",
            "Kurt", "Turan", "Keskin", "Tas", "Erdogan", "Bilgin", "Orhan", "Kilic", "Isik",
            "Korkmaz", "Selcuk", "Duman", "Genc", "Koyuncu",
        ],
    },
    // Polish
    NamePool {
        first_names: &[
            "Jakub",
            "Anna",
            "Kacper",
            "Maria",
            "Michał",
            "Katarzyna",
            "Szymon",
            "Małgorzata",
            "Piotr",
            "Agnieszka",
            "Bartosz",
            "Barbara",
            "Krzysztof",
            "Ewa",
            "Tomasz",
            "Elżbieta",
            "Marcin",
            "Zofia",
            "Łukasz",
            "Magdalena",
            "Rafał",
            "Joanna",
            "Mateusz",
            "Aleksandra",
            "Dawid",
            "Monika",
            "Adrian",
            "Paulina",
            "Wojciech",
            "Natalia",
            "Patryk",
            "Marta",
        ],
        last_names: &[
            "Nowak",
            "Kowalski",
            "Wiśniewski",
            "Wójcik",
            "Kowalczyk",
            "Kamiński",
            "Lewandowski",
            "Zieliński",
            "Szymański",
            "Dąbrowski",
            "Kozłowski",
            "Jankowski",
            "Mazur",
            "Kwiatkowski",
            "Wojciechowski",
            "Krawczyk",
            "Piotrowicz",
            "Grabowski",
            "Pawlak",
            "Michalski",
            "Stankiewicz",
            "Witkowski",
            "Walczak",
            "Szczepański",
            "Zawadzki",
            "Sadowski",
            "Jakubowski",
            "Czarnecki",
            "Sikora",
            "Ostrowski",
            "Adamczyk",
            "Jabłoński",
        ],
    },
];

const STREET_NAMES: &[&str] = &[
    "Main St",
    "Oak Ave",
    "Elm St",
    "Maple Dr",
    "Broadway",
    "Cedar Ln",
    "Pine St",
    "Washington Blvd",
    "Lake Dr",
    "Hill Rd",
    "Park Ave",
    "Spring St",
    "Church St",
    "River Rd",
    "Highland Ave",
    "Forest Dr",
    "Sunset Blvd",
    "Mill St",
    "School St",
    "Center St",
    "View Ave",
    "North St",
    "Cherry Ln",
    "Walnut St",
    "Locust Ave",
    "Meadow Dr",
    "Ridge Rd",
    "Valley Blvd",
    "Garden St",
    "Brook Ln",
    "Ocean Ave",
    "Harbor Blvd",
    "Bay St",
    "Coastal Hwy",
    "Beach Dr",
    "Mountain Rd",
    "Summit Ave",
    "Peak Dr",
    "Plaza Blvd",
    "King St",
    "Queen Ave",
    "Prince Ln",
    "Royal Blvd",
    "Station St",
    "Depot Ave",
    "Railroad Blvd",
    "Terminal Dr",
    "Gateway Blvd",
    "Willow Ct",
    "Birch Way",
    "Spruce Cir",
    "Sycamore Dr",
    "Dogwood Ln",
    "Windsor Rd",
    "Cambridge Ave",
    "Oxford Ct",
    "Wellington Blvd",
    "Industrial Dr",
    "Commerce Blvd",
    "Tech Park Dr",
    "Enterprise Rd",
];

const CITIES: &[&str] = &[
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "Indianapolis",
    "San Francisco",
    "Seattle",
    "Denver",
    "Nashville",
    "Oklahoma City",
    "El Paso",
    "Washington",
    "Boston",
    "Las Vegas",
    "Portland",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Mesa",
    "Atlanta",
    "Kansas City",
    "Omaha",
    "Colorado Springs",
    "Raleigh",
    "Long Beach",
    "Virginia Beach",
    "Miami",
    "Oakland",
    "Minneapolis",
    "Tampa",
    "Tulsa",
    "Arlington",
    "New Orleans",
    "Cleveland",
    "Anaheim",
    "Honolulu",
    "Riverside",
    "Lexington",
    "London",
    "Manchester",
    "Edinburgh",
    "Birmingham",
    "Liverpool",
    "Leeds",
    "Glasgow",
    "Bristol",
    "Sheffield",
    "Newcastle",
    "Cambridge",
    "Oxford",
    "Canterbury",
    "York",
    "Brighton",
    "Bath",
    "Nottingham",
    "Belfast",
    "Cardiff",
    "Aberdeen",
    "Dundee",
    "Southampton",
    "Portsmouth",
    "Toronto",
    "Vancouver",
    "Montreal",
    "Calgary",
    "Ottawa",
    "Edmonton",
    "Halifax",
    "Quebec City",
    "Winnipeg",
    "Victoria",
    "Saskatoon",
    "Regina",
    "Kitchener",
    "Burnaby",
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Auckland",
    "Adelaide",
    "Wellington",
    "Christchurch",
    "Gold Coast",
    "Hobart",
    "Darwin",
    "Dunedin",
    "Tauranga",
    "Newcastle",
    "Geelong",
    "Paris",
    "Berlin",
    "Rome",
    "Madrid",
    "Amsterdam",
    "Vienna",
    "Zurich",
    "Brussels",
    "Stockholm",
    "Oslo",
    "Copenhagen",
    "Helsinki",
    "Dublin",
    "Lisbon",
    "Prague",
    "Budapest",
    "Warsaw",
    "Munich",
    "Hamburg",
    "Milan",
    "Barcelona",
    "Florence",
    "Venice",
    "Reykjavik",
    "Tallinn",
    "Riga",
    "Vilnius",
    "Luxembourg",
    "Tokyo",
    "Osaka",
    "Kyoto",
    "Seoul",
    "Beijing",
    "Shanghai",
    "Hong Kong",
    "Singapore",
    "Bangkok",
    "Dubai",
    "Mumbai",
    "New Delhi",
    "Jakarta",
    "Manila",
    "Kuala Lumpur",
    "Taipei",
    "Istanbul",
    "Tel Aviv",
    "Riyadh",
    "Doha",
    "Abu Dhabi",
    "Kolkata",
    "Shenzhen",
    "Guangzhou",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Mexico City",
    "Buenos Aires",
    "Sao Paulo",
    "Rio de Janeiro",
    "Lima",
    "Bogota",
    "Santiago",
    "Quito",
    "Montevideo",
    "Caracas",
    "Havana",
    "San Jose",
    "Panama City",
    "San Juan",
    "Santo Domingo",
    "Guatemala City",
    "Medellin",
    "Cairo",
    "Cape Town",
    "Johannesburg",
    "Lagos",
    "Nairobi",
    "Casablanca",
    "Marrakech",
    "Tunis",
    "Dakar",
    "Accra",
    "Addis Ababa",
    "Kigali",
    "Dar es Salaam",
    "Kampala",
    "Lusaka",
    "Windhoek",
    "Gaborone",
    "Algiers",
    "Alexandria",
    "Rabat",
    "Pretoria",
    "Jerusalem",
    "Beirut",
    "Amman",
    "Baghdad",
    "Tehran",
    "Kuwait City",
    "Muscat",
    "Manama",
    "Antalya",
];

const STATES: &[&str] = &[
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS",
    "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY",
    "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV",
    "WI", "WY",
];

const COUNTRIES: &[&str] = &[
    "United States",
    "Canada",
    "United Kingdom",
    "Germany",
    "France",
    "Australia",
    "Japan",
    "Brazil",
    "India",
    "Mexico",
    "Italy",
    "Spain",
    "Netherlands",
    "Sweden",
    "Norway",
    "Switzerland",
    "Singapore",
    "South Korea",
    "New Zealand",
    "Ireland",
    "Argentina",
    "Austria",
    "Belgium",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Czech Republic",
    "Denmark",
    "Egypt",
    "Finland",
    "Greece",
    "Hungary",
    "Iceland",
    "Indonesia",
    "Israel",
    "Kenya",
    "Malaysia",
    "Morocco",
    "Nigeria",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Romania",
    "Saudi Arabia",
    "South Africa",
    "Thailand",
    "Turkey",
    "Ukraine",
    "United Arab Emirates",
    "Vietnam",
    "Croatia",
    "Ethiopia",
    "Ghana",
    "Jordan",
    "Lithuania",
    "Malta",
    "Nepal",
    "Panama",
    "Qatar",
    "Russia",
    "Slovakia",
    "Slovenia",
    "Sri Lanka",
    "Tanzania",
    "Tunisia",
    "Uruguay",
    "Venezuela",
    "Bangladesh",
    "Bulgaria",
    "Kazakhstan",
    "Kuwait",
    "Luxembourg",
    "Madagascar",
    "Maldives",
    "Mauritius",
    "Monaco",
    "Mongolia",
    "Myanmar",
    "Namibia",
    "Oman",
    "Pakistan",
    "Paraguay",
    "Rwanda",
    "Senegal",
    "Serbia",
    "Taiwan",
    "Uganda",
    "Uzbekistan",
    "Zambia",
];

const COMPANY_NAMES: &[&str] = &[
    "TechCorp",
    "Global Solutions",
    "Innovate Inc",
    "Apex Systems",
    "NexGen Technologies",
    "Pinnacle Group",
    "Summit Analytics",
    "Meridian Health",
    "Vanguard Industries",
    "Horizon Media",
    "Titan Manufacturing",
    "Sage Financial",
    "Quantum Computing",
    "Fusion Dynamics",
    "Legacy Enterprises",
    "Ironclad Security",
    "Polaris Ventures",
    "Atlas Global",
    "NovaStar Robotics",
    "Helix Biotech",
    "Stratus Cloud Services",
    "Aether Networks",
    "Glyph Design Studio",
    "Prism Analytics",
    "Vortex Gaming",
    "Zephyr Aerospace",
    "Arbor Energy",
    "Oakwood Realty",
    "Cobalt Mining Corp",
    "Ruby Media Group",
    "Ember Creative",
    "Pulse Fitness",
    "Cascade Water Systems",
    "TerraGreen Agricorp",
    "Lumen Education",
    "Brave Frontier Logistics",
    "Saffron Hospitality",
    "Cypress Insurance",
    "Dragonfly IoT",
    "Pelican Aviation",
    "Raven Cybersecurity",
    "Falcon Defense",
    "Sparrow Digital",
    "Kingfisher Marine",
    "Osprey Consulting",
    "Phoenix Reinsurance",
    "Jade Construction",
    "Amber Electronics",
    "Obsidian Ventures",
    "Topaz Semiconductor",
    "Rocket Communications",
    "Satellite Works",
    "Redwood Timber",
    "Maple Leaf Foods",
    "Blue Horizon Travel",
    "Silverpeak Mining",
    "Orbital Sciences",
    "Solaris Energy",
    "Nebula Cloud",
    "Cascade Microchips",
    "Riverstone Partners",
    "Prairie AgTech",
    "Savanna Biologics",
    "Oceanview Properties",
    "Highland Ventures",
    "Lakefront Capital",
    "Bayview Consulting",
    "Sierra Nevada Brewing",
    "Aspen Ski Resorts",
    "Alpine Outfitters",
    "Pacific Rim Trading",
    "Atlantic Meridian Bank",
    "Mediterranean Shipping",
    "Baltic Engineering",
    "Nordic Health",
];

const JOB_TITLES: &[&str] = &[
    "Software Engineer",
    "Data Scientist",
    "Product Manager",
    "Design Director",
    "Chief Technology Officer",
    "Marketing Lead",
    "Financial Analyst",
    "Operations Manager",
    "Human Resources Director",
    "Sales Executive",
    "Research Scientist",
    "UX Designer",
    "DevOps Engineer",
    "Business Analyst",
    "Project Coordinator",
    "QA Lead",
    "Systems Architect",
    "Technical Writer",
    "Account Executive",
    "Consultant",
    "Frontend Developer",
    "Backend Engineer",
    "Full Stack Developer",
    "Mobile Developer",
    "Cloud Architect",
    "Security Engineer",
    "Network Administrator",
    "Database Administrator",
    "Machine Learning Engineer",
    "AI Researcher",
    "Data Engineer",
    "Analytics Manager",
    "Creative Director",
    "Art Director",
    "Graphic Designer",
    "Content Strategist",
    "SEO Specialist",
    "Social Media Manager",
    "Brand Manager",
    "PR Director",
    "Chief Financial Officer",
    "VP of Sales",
    "Regional Manager",
    "Team Lead",
    "Agile Coach",
    "Scrum Master",
    "Release Manager",
    "Platform Engineer",
    "Embedded Systems Engineer",
    "Firmware Developer",
    "Hardware Engineer",
    "Mechanical Engineer",
    "Civil Engineer",
    "Electrical Engineer",
    "Chemical Engineer",
    "Biomedical Engineer",
    "Environmental Scientist",
    "Lab Technician",
    "Clinical Researcher",
    "Pharmacologist",
    "Surgeon",
    "Pediatrician",
    "Neurologist",
    "Cardiologist",
    "Attorney",
    "Paralegal",
    "Judge",
    "Legal Counsel",
    "Professor",
    "Dean of Faculty",
    "Research Fellow",
    "Postdoctoral Researcher",
    "High School Teacher",
    "Elementary Educator",
    "Curriculum Designer",
    "Education Consultant",
    "Chef de Cuisine",
    "Sous Chef",
    "Pastry Chef",
    "Restaurant Manager",
    "Pilot",
    "Flight Attendant",
    "Air Traffic Controller",
    "Logistics Coordinator",
    "Journalist",
    "Editor",
    "Photojournalist",
    "Broadcast Anchor",
    "Urban Planner",
    "Architect",
    "Interior Designer",
    "Landscape Architect",
    "Physicist",
    "Chemist",
    "Biologist",
    "Astronomer",
    "Economist",
    "Sociologist",
    "Psychologist",
    "Historian",
    "Librarian",
    "Museum Curator",
    "Archivist",
    "Conservator",
    "Firefighter",
    "Police Officer",
    "EMT",
    "Paramedic",
    "Farmer",
    "Veterinarian",
    "Zoologist",
    "Marine Biologist",
    "Astronaut",
    "Geologist",
    "Meteorologist",
    "Oceanographer",
];

const EMAIL_DOMAINS: &[&str] = &[
    "gmail.com",
    "yahoo.com",
    "outlook.com",
    "protonmail.com",
    "icloud.com",
    "hotmail.com",
    "mail.com",
    "zoho.com",
    "fastmail.com",
    "aol.com",
    "tutanota.com",
    "gmx.com",
    "yandex.com",
    "hey.com",
    "posteo.net",
    "disroot.org",
    "riseup.net",
    "kolabnow.com",
    "runbox.com",
    "soverin.net",
    "migadu.com",
    "mailbox.org",
    "startmail.com",
    "ctemplar.com",
    "pm.me",
    "company.org",
    "business.net",
    "consulting.io",
    "enterprise.co",
    "mail.ru",
    "rediffmail.com",
    "naver.com",
    "daum.net",
    "qq.com",
    "163.com",
    "126.com",
    "sina.com",
    "web.de",
    "gmx.de",
    "t-online.de",
    "freenet.de",
    "ymail.com",
    "inbox.com",
    "email.com",
    "rocketmail.com",
];

const DOMAIN_SUFFIXES: &[&str] = &[
    "com",
    "net",
    "org",
    "io",
    "co",
    "app",
    "dev",
    "tech",
    "info",
    "biz",
    "me",
    "tv",
    "ai",
    "cloud",
    "digital",
    "solutions",
    "global",
    "media",
    "design",
    "systems",
    "network",
    "international",
    "xyz",
    "online",
    "site",
    "space",
    "world",
    "pro",
    "work",
    "blog",
    "agency",
    "consulting",
    "management",
    "ventures",
    "partners",
    "today",
    "email",
    "software",
    "studio",
    "art",
    "travel",
    "health",
    "edu",
    "gov",
    "mil",
];

const USERNAMES: &[&str] = &[
    "jdoe",
    "asmith",
    "mjohnson",
    "kwilson",
    "rbrown",
    "lperez",
    "dlee",
    "cmartin",
    "taylor",
    "anderson",
    "jackson",
    "thompson",
    "white",
    "harris",
    "clark",
    "lewis",
    "robinson",
    "walker",
    "young",
    "king",
    "wright",
    "scott",
    "green",
    "baker",
    "hill",
    "torres",
    "nguyen",
    "rivera",
    "campbell",
    "mitchell",
    "alex_j",
    "max_d",
    "sarahk",
    "chrisb",
    "nina_r",
    "omar_h",
    "lina_m",
    "zack_w",
    "emma_t",
    "ryan_f",
    "zara_p",
    "jake_n",
    "maya_s",
    "ethan_c",
    "isla_v",
    "noah_g",
    "aria_l",
    "leo_d",
    "mila_q",
    "kai_z",
    "piper_x",
    "axel_j",
    "ruby_k",
    "cole_w",
    "hazel_r",
    "felix_m",
    "ivy_p",
    "aaron_b",
    "luna_c",
    "liam_h",
    "tech_guru",
    "dev_ninja",
    "code_wiz",
    "data_dr",
    "pixel_master",
    "cloud_king",
    "logic_bot",
    "byte_rider",
    "shell_master",
    "script_kid",
    "pixel_pusher",
    "night_owl",
    "early_bird",
    "sunset_chaser",
    "wave_rider",
    "hackattack",
    "binary_boss",
    "pythonista",
    "rustacean",
    "jvm_wizard",
    "terminal_x",
    "vim_master",
    "emacs_guru",
    "open_source_maven",
];

const PHONE_NUMBERS: &[&str] = &[
    "(555) 123-4567",
    "(555) 234-5678",
    "(555) 345-6789",
    "(555) 456-7890",
    "(555) 567-8901",
    "(555) 678-9012",
    "(555) 789-0123",
    "(555) 890-1234",
    "(555) 901-2345",
    "(555) 012-3456",
    "(555) 246-8135",
    "(555) 369-2580",
    "(555) 147-2589",
    "(555) 258-3691",
    "(555) 369-1472",
    "(555) 481-5162",
    "(555) 516-2734",
    "(555) 627-3845",
    "(555) 738-4956",
    "(555) 849-5067",
    "(212) 555-0147",
    "(310) 555-2389",
    "(415) 555-6791",
    "(617) 555-8302",
    "(312) 555-4493",
    "(206) 555-5604",
    "(305) 555-6715",
    "(214) 555-7826",
    "(303) 555-8937",
    "(404) 555-9048",
    "(713) 555-1159",
    "(602) 555-2260",
    "+44 20 7946 0958",
    "+44 7700 900 491",
    "+44 161 496 0123",
    "+44 131 496 0456",
    "+33 1 23 45 67 89",
    "+33 6 12 34 56 78",
    "+49 30 1234567",
    "+49 89 7654321",
    "+39 06 1234 5678",
    "+34 91 123 45 67",
    "+31 20 123 4567",
    "+46 8 123 456",
    "+45 33 12 34 56",
    "+47 22 12 34 56",
    "+358 9 123 4567",
    "+61 2 9123 4567",
    "+61 3 9234 5678",
    "+61 7 9345 6789",
    "+81 3 1234 5678",
    "+81 6 2345 6789",
    "+82 2 123 4567",
    "+86 10 1234 5678",
    "+91 22 1234 5678",
    "+65 6123 4567",
    "+60 3 1234 5678",
    "+971 4 123 4567",
    "+974 1234 5678",
    "+52 55 1234 5678",
    "+55 11 91234 5678",
    "+54 11 1234 5678",
    "+56 2 2123 4567",
    "+57 1 123 4567",
    "+27 11 123 4567",
    "+27 21 234 5678",
    "+20 2 1234 5678",
    "+234 1 234 5678",
    "+254 20 123 4567",
];

const CREDIT_CARDS: &[&str] = &[
    "4111 1111 1111 1111",
    "4012 8888 8888 1881",
    "4532 1111 1111 1111",
    "4222 2222 2222 2222",
    "4716 1000 0000 0000",
    "4929 0000 0000 0006",
    "4485 0000 0000 0004",
    "4539 7910 0000 0001",
    "5500 0000 0000 0004",
    "5555 5555 5555 4444",
    "5105 1051 0510 5100",
    "5200 0000 0000 0007",
    "5300 0000 0000 0005",
    "5400 0000 0000 0003",
    "2221 0000 0000 0009",
    "3400 0000 0000 009",
    "3700 0000 0000 002",
    "3714 4963 5398 431",
    "3782 8224 6310 005",
    "6011 0000 0000 0004",
    "6011 1111 1111 1117",
    "6229 2600 0000 0000",
    "6229 2500 0000 0000",
    "3000 0000 0000 04",
    "3011 1111 1111 11",
    "3030 0000 0000 00",
    "3852 0000 0232 37",
    "3530 1113 3330 0000",
    "3566 0020 2036 0505",
    "3566 1111 1111 1113",
    "3528 0000 0000 0007",
    "6200 0000 0000 0005",
    "6212 3456 7890 0000",
    "6221 0000 0000 0000",
    "6210 0000 0000 0002",
    "6217 0000 0000 0003",
];

fn pick_culturally_consistent_name() -> (String, String) {
    let mut rng = rand::rng();
    let pool = &NAME_POOLS[rng.random_range(0..NAME_POOLS.len())];
    let first = pool.first_names[rng.random_range(0..pool.first_names.len())];
    let last = pool.last_names[rng.random_range(0..pool.last_names.len())];
    (first.to_string(), last.to_string())
}

fn pick<'a>(pool: &'a [&'a str]) -> &'a str {
    let mut rng = rand::rng();
    pool[rng.random_range(0..pool.len())]
}

pub fn resolve(key: &str) -> Option<String> {
    let modifier = key.strip_prefix("mock.")?.trim();

    match parse_modifier(modifier)? {
        ("name", None) => {
            let (first, last) = pick_culturally_consistent_name();
            Some(format!("{} {}", first, last))
        }
        ("first_name", None) => {
            let mut rng = rand::rng();
            let pool = &NAME_POOLS[rng.random_range(0..NAME_POOLS.len())];
            Some(pool.first_names[rng.random_range(0..pool.first_names.len())].to_string())
        }
        ("last_name", None) => {
            let mut rng = rand::rng();
            let pool = &NAME_POOLS[rng.random_range(0..NAME_POOLS.len())];
            Some(pool.last_names[rng.random_range(0..pool.last_names.len())].to_string())
        }
        ("address", None) => Some(format_address()),
        ("city", None) => Some(pick(CITIES).to_string()),
        ("state", None) => Some(pick(STATES).to_string()),
        ("zip_code", None) => Some(format!("{:05}", rand::rng().random_range(10000..99999))),
        ("country", None) => Some(pick(COUNTRIES).to_string()),
        ("email", None) => {
            let (first, last) = pick_culturally_consistent_name();
            Some(format!(
                "{}.{}@{}",
                first.to_lowercase(),
                last.to_lowercase(),
                pick(EMAIL_DOMAINS)
            ))
        }
        ("domain", None) => Some(format_domain()),
        ("username", None) => Some(pick(USERNAMES).to_string()),
        ("company", None) => Some(pick(COMPANY_NAMES).to_string()),
        ("job_title", None) => Some(pick(JOB_TITLES).to_string()),
        ("credit_card", None) => Some(pick(CREDIT_CARDS).to_string()),
        ("phone_number", None) => Some(pick(PHONE_NUMBERS).to_string()),
        ("cell_number", None) => Some(pick(PHONE_NUMBERS).to_string()),
        _ => None,
    }
}

fn parse_modifier(input: &str) -> Option<(&str, Option<&str>)> {
    if let Some(paren_idx) = input.find('(') {
        let variant = input[..paren_idx].trim();
        let (args, trailing) = scan_parenthesized(&input[paren_idx..])?;
        if !variant.is_empty() && trailing.trim().is_empty() {
            Some((variant, Some(args)))
        } else {
            None
        }
    } else if input.contains(')') {
        None
    } else {
        Some((input.trim(), None)).filter(|(variant, _)| !variant.is_empty())
    }
}

fn scan_parenthesized(input: &str) -> Option<(&str, &str)> {
    if !input.starts_with('(') {
        return None;
    }

    let mut depth = 0usize;
    let mut start = None;

    for (idx, ch) in input.char_indices() {
        match ch {
            '(' => {
                if depth == 0 {
                    start = Some(idx + ch.len_utf8());
                }
                depth += 1;
            }
            ')' => {
                if depth == 0 {
                    return None;
                }
                depth -= 1;
                if depth == 0 {
                    let start = start?;
                    return Some((input[start..idx].trim(), &input[idx + 1..]));
                }
            }
            _ => {}
        }
    }

    None
}

fn format_address() -> String {
    let mut rng = rand::rng();
    format!(
        "{} {}, {}, {} {}",
        rng.random_range(1..9999),
        pick(STREET_NAMES),
        pick(CITIES),
        pick(STATES),
        rng.random_range(10000..99999),
    )
}

fn format_domain() -> String {
    format!(
        "{}.{}",
        sanitize_domain_label(pick(USERNAMES)),
        pick(DOMAIN_SUFFIXES)
    )
}

fn sanitize_domain_label(input: &str) -> String {
    let label = input
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() {
                ch.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect::<String>()
        .trim_matches('-')
        .to_string();

    if label.is_empty() {
        "example".to_string()
    } else {
        label
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_identity_variants() {
        assert!(!resolve("mock.name").unwrap().trim().is_empty());
        assert!(!resolve("mock.first_name").unwrap().trim().is_empty());
        assert!(!resolve("mock.last_name").unwrap().trim().is_empty());
    }

    #[test]
    fn mock_name_gives_culturally_consistent_names() {
        for _ in 0..500 {
            let name = resolve("mock.name").unwrap();
            let (first, last) = name.split_once(' ').unwrap();
            // Some names (e.g. "Martina") appear in multiple pools' first_names,
            // so .position() is unreliable. Instead check there exists at least
            // one pool where both names appear together.
            let consistent = NAME_POOLS
                .iter()
                .any(|pool| pool.first_names.contains(&first) && pool.last_names.contains(&last));
            assert!(
                consistent,
                "Cross-cultural name mix: {} {} — no single pool contains both",
                first, last
            );
        }
    }

    #[test]
    fn mock_email_gives_culturally_consistent_names() {
        for _ in 0..500 {
            let email = resolve("mock.email").unwrap();
            let local = email.split('@').next().unwrap();
            let (first, last) = local.split_once('.').unwrap();
            // The email generation uses first.to_lowercase() / last.to_lowercase()
            // (Unicode-aware), so compare using to_lowercase() instead of
            // eq_ignore_ascii_case which would miss accented characters.
            let consistent = NAME_POOLS.iter().any(|pool| {
                pool.first_names.iter().any(|n| n.to_lowercase() == first)
                    && pool.last_names.iter().any(|n| n.to_lowercase() == last)
            });
            assert!(
                consistent,
                "Cross-cultural email name mix: {} — no single pool contains both",
                email
            );
        }
    }

    #[test]
    fn resolves_geography_variants() {
        let address = resolve("mock.address").unwrap();
        assert!(address.contains(','));
        assert!(!resolve("mock.city").unwrap().trim().is_empty());
        assert!(!resolve("mock.state").unwrap().trim().is_empty());
        assert!(!resolve("mock.zip_code").unwrap().trim().is_empty());
        assert!(!resolve("mock.country").unwrap().trim().is_empty());
    }

    #[test]
    fn resolves_web_variants() {
        let email = resolve("mock.email").unwrap();
        assert!(email.contains('@'));
        assert!(!resolve("mock.username").unwrap().trim().is_empty());
        assert!(resolve("mock.domain").unwrap().contains('.'));
    }

    #[test]
    fn resolves_professional_variants() {
        assert!(!resolve("mock.company").unwrap().trim().is_empty());
        assert!(!resolve("mock.job_title").unwrap().trim().is_empty());
    }

    #[test]
    fn resolves_financial_and_communication_variants() {
        assert!(!resolve("mock.credit_card").unwrap().trim().is_empty());
        assert!(!resolve("mock.phone_number").unwrap().trim().is_empty());
        assert!(!resolve("mock.cell_number").unwrap().trim().is_empty());
    }

    #[test]
    fn rejects_pruned_variants() {
        assert_eq!(resolve("mock.password(12)"), None);
        assert_eq!(resolve("mock.bs"), None);
        assert_eq!(resolve("mock.status_code"), None);
    }
}
